Page fixes
dynobjx/dynobjx.github.io pull request #2
Opened 2017-01-03 07:41 UTC by klBiazon

2017-01-04 04:02 UTC, mesantiago approved these changes

2017-01-04 04:30 UTC, blesildaramirez commented on main.css
> +    background-image: url('rsz_01_initial%20image.png');
Change the directory of this image using the commit hash and not the master branch. Also use the rawgit cdn to optimize this image.

2017-01-04 04:33 UTC, blesildaramirez commented on main.css
> +    background-image: url('rsz_02_image.png');
Use the raw git file directory (cdn-based) of this image. Again, using the commit hash URL.

2017-01-04 04:34 UTC, blesildaramirez requested changes
Requested changes are already commented in this pull request.

2017-01-05 04:27 UTC, blesildaramirez approved these changes

2017-01-05 04:29 UTC, merged